#!/bin/bash
########################################################################
# Build script for check_sht31
# Copyright (c) 2017 Frostbyte <frostbytegr@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

tagERROR='\e[0m'"[ "'\e[1;31m'"ERROR"'\e[0m'" ]"
tagOK='\e[0m'"[ "'\e[1;32m'"OK"'\e[0m'" ]"
tagGCC='\e[0m'"[ "'\e[1;33m'"GCC"'\e[0m'" ]"

echo "Checking dependencies.."
binGcc=`which gcc`
if [ -z $binGcc ]; then
	echo -e "$tagERROR Cannot find gcc. (hint: sudo apt-get gcc)"
	exit 1
else
	echo -e "$tagOK Found gcc: $binGcc"
fi

if [ ! -d "bin" ] && ! mkdir bin; then
	echo -e "$tagERROR Failed to create the bin folder."
	exit 1
fi

echo "Compiling.."
gccOutput=$($binGcc -o bin/check_sht31 check_sht31.c nagioshelper.c sht31.c -fdiagnostics-color=always 2>&1)
gccResult=$?

if [[ $1 == "-v" ]]; then
	oIFS=$IFS
	IFS=$'\n'
	for line in $gccOutput; do
		echo -e "$tagGCC \c" && echo $line
	done
	IFS=$oIFS
fi

if [[ $gccResult == 0 ]]; then
	echo -e "$tagOK Compile successful. The executable can be found under: bin/check_sht31"
else
	echo -e "$tagERROR Compile failed."
fi
exit $gccResult
